volumes:
  romm_redis_data:

services:
  romm:
    image: ${IMAGE_ROMM}
    container_name: romm
    environment:
      - DB_HOST=romm-db
      - DB_NAME=${DB_NAME} # Should match MYSQL_DATABASE in mariadb
      - DB_USER=${DB_USER} # Should match MYSQL_USER in mariadb
      - DB_PASSWD=${DB_PASSWD} # Should match MYSQL_PASSWORD in mariadb
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID} # Generate an ID and SECRET in IGDB
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET} # https://api-docs.igdb.com/#account-creation
      - MOBYGAMES_API_KEY=${MOBYGAMES_API_KEY} # https://www.mobygames.com/info/api/
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY} # Generate a key with `openssl rand -hex 32`
    volumes:
      - ${SYS_LIBRARY_PATH}:${CON_LIBRARY_PATH} # Your game library
      - ${SYS_CONFIG_PATH}:${CON_CONFIG_PATH} # Path where config.yml is stored
      - ${SYS_ASSETS_PATH}:${CON_ASSETS_PATH} # Uploaded saves, states, etc.
      - ${SYS_RESOURCES_PATH}:${CON_RESOURCES_PATH} # Resources fetched from IGDB (covers, screenshots, etc.)
      - romm_redis_data:/redis-data # Cached data for background tasks
    ports:
      - ${SYS_ROMM_PORT}:${CON_ROMM_PORT}
    depends_on:
      - romm_db
    restart: "unless-stopped"

  romm_db:
    image: ${IMAGE_ROMM_DB}
    container_name: romm-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
    volumes:
      - ${SYS_DATABASE_PATH}:${CON_DATABASE_PATH}
    ports:
      - ${SYS_DB_PORT}:${CON_DB_PORT}
    restart: "unless-stopped"
