version: '3'
services:
  romm:
    image: ${IMAGE_ROMM}
    container_name: romm
    environment:
      - ROMM_DB_DRIVER=${ROMM_DB_DRIVER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
      - ROMM_AUTH_ENABLED=${ROMM_AUTH_ENABLED}
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY}
      - ROMM_AUTH_USERNAME=${ROMM_AUTH_USERNAME}
      - ROMM_AUTH_PASSWORD=${ROMM_AUTH_PASSWORD}
      - ENABLE_EXPERIMENTAL_REDIS=${ENABLE_EXPERIMENTAL_REDIS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ENABLE_SCHEDULED_RESCAN=${ENABLE_SCHEDULED_RESCAN}
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=${ENABLE_RESCAN_ON_FILESYSTEM_CHANGE}
      - ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB=${ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB}
      - ENABLE_SCHEDULED_UPDATE_MAME_XML=${ENABLE_SCHEDULED_UPDATE_MAME_XML}
    volumes:
      - ${LIBRARY_PATH}:/romm/library
      - ${CONFIG_PATH}:/romm/config.yml
      - ${RESOURCES_PATH}:/romm/resources
      - ${DATABASE_PATH}:/romm/database
    ports:
      - ${ROMM_PORT}:8080
    depends_on:
      - romm_db
    restart: "unless-stopped"


  romm_db:
    image: ${IMAGE_ROMM_DB}
    container_name: romm_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_DATABASE=romm
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
    volumes:
      - ${DB_CONFIG_PATH}:/config
    ports:
      - ${DB_PORT}:3306
    restart: "unless-stopped"

  redis:
    image: ${IMAGE_ROMM_REDIS}
    container_name: redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379


