version: "3"

services:
  vaultwarden:
    image: ${IMAGE}
    container_name: vaultwarden
    volumes:
      - ${SYS_VOL_DATA}:${CON_VOL_DATA}
    ports:
      - ${SYS_PORT}:${CON_PORT}
    restart: "no"