version: "3.8"

services:
  node_exporter:
    image: ${IMAGE_NODE}
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    ports:
      - ${SYS_PORT_NODE_EXP}:${CON_PORT_NODE_EXP}
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    restart: "always"
