services:
  filebrowser:
    image: ${IMAGE}
    container_name: filebrowser
    environment:
      - TZ=${TZ}
    volumes:
      - ${SYS_VOL_FILESYSTEM}:${CON_VOL_FILESYSTEM}
      - ${SYS_VOL_DB}:${CON_VOL_DB}
      - ${SYS_VOL_CONFIG}:${CON_VOL_CONFIG}
    ports:
      - ${SYS_PORT}:${CON_PORT}
    restart: "unless-stopped"
    
