version: '3'

services:
  registry:
    image: ${IMAGE}
    container_name: registry
    volumes:
      - ${SYS_VOL_REGISTRY}:${CON_VOL_REGISTRY}
      - ${SYS_VOL_CREDENTIALS}:${CON_VOL_CREDENTIALS}
    ports:
      - ${SYS_PORT}:${CON_PORT}
    restart: "always"

  registry-front:
    image: ${IMAGE_FRONT}
    container_name: registry-front
    ports:
      - ${SYS_PORT_FRONT}:${CON_PORT_FRONT}
    environment:
      - REGISTRY_TITLE=${REGISTRY_TITLE}
      - REGISTRY_URL=${REGISTRY_URL}
      - SINGLE_REGISTRY=${SINGLE_REGISTRY}
    depends_on:
      - registry