version: '3'

services:
  registry:
    image: ${IMAGE}
    container_name: registry
    volumes:
      - ${SYS_VOL_REGISTRY}:${CON_VOL_REGISTRY}
    ports:
      - ${SYS_PORT}:${CON_PORT}
    restart: "always"