version: '3'

services:
  registry:
    image: ${IMAGE}
    container_name: registry
    volumes:
      - ${SYS_VOL_REGISTRY}:${CON_VOL_REGISTRY}
    ports:
      - ${SYS_PORT}:${CON_PORT}
    environment:
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin=${REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin}
    restart: "always"

  registry-front:
    image: ${IMAGE_FRONT}
    container_name: registry-front
    ports:
      - ${SYS_PORT_FRONT}:${CON_PORT_FRONT}
    environment:
      - REGISTRY_TITLE=${REGISTRY_TITLE}
      - REGISTRY_URL=${REGISTRY_URL}
      - SINGLE_REGISTRY=${SINGLE_REGISTRY}
    depends_on:
      - registry