services:
  kavita:
    image: ${IMAGE}
    container_name: kavita
    volumes:
      - ${SYS_VOL_CONFIG}:${CON_VOL_CONFIG}
      - ${SYS_VOL_COMICS}:${CON_VOL_COMICS}
      - ${SYS_VOL_BOOKS}:${CON_VOL_BOOKS}
    ports:
      - ${SYS_PORT}:${CON_PORT}
    restart: "unless-stopped"
    