version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: ${IMAGE}
    volumes:
      - ${SYS_VOL_CONF}:${CON_VOL_CONF}
      - /etc/localtime:/etc/localtime:ro
    restart: "always"
    privileged: true
    network_mode: host