version: "3"

services:
  wikijs:
    image: ${IMAGE}
    container_name: wikijs
    volumes:
      - ${SYS_VOL_CONF}:${CON_VOL_CONF}
      - ${SYS_VOL_DATA}:${CON_VOL_DATA}
    ports:
      - ${SYS_PORT}:${CON_PORT}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: "no"